### ISSUE TITLE
BUG: role with null value added to the history on content blocked due to Safety reasons

### ISSUE THREAD

**Issue by Flucadetena** [google-gemini/generative-ai-dart#197]
### Description of the bug:

When using the chat mode and sending messages instead of streaming (using the method `sendMessage` instead of `sendMessageStream`) , the blocked responses from the ai will be added to the `_history` with a `null` role. Throwing an exception and breaking the `chatSession` as the multi-turn mode will force the conversation to alternate between user and model.

This normally throughs this Exception:
```
I/flutter (29978): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (29978): The following exception was thrown Init App Services Fatal error:
I/flutter (29978): Please use a valid role: user, model.
I/flutter (29978): 
I/flutter (29978): #0      parseGenerateContentResponse (package:google_generative_ai/src/api.dart:583:54)
I/flutter (29978): <asynchronous suspension>
I/flutter (29978): #1      ChatSession.sendMessage (package:google_generative_ai/src/chat.dart:67:24)
I/flutter (29978): <asynchronous suspension>
I/flutter (29978): #2      ChatSession.sendMessage.<anonymous closure> (package:firebase_vertexai/src/vertex_chat.dart:71:15)
I/flutter (29978): <asynchronous suspension>
I/flutter (29978): ---------------------------------------------------- 
```

### Actual vs expected behavior:

If a responses is flagged and blocked, it should not be added to the `history` allowing the developer to handle the error and either retry the generation or add a generic response from the ai to continue the conversation naturally.

**Comment by Flucadetena** [comment]
Awesome @natebosch thank you for the update.

**Comment by Flucadetena** [comment]
Hi team,

The issue is not solve with this fix as the main problem is the lack of answer from the model in the history.

You can use this example repo I created and follow the instructions and you will se the chat breaks completely. https://github.com/firebase/flutterfire/issues/13104

The only two solutions I can think of, that I currently use in my own code are:

- Give the option to the developer to pass a default message in case the content gets blocked. This would solve the problem of having a "user>model>user>model" as multi-turn requests.
- Before every generation, check the history and join any content that comes from the same role. This is what Studio AI and the JS package do.

Hope it helps, thanks for the great job.
